# Set true color
set -g default-terminal "screen-256color"

# Allow mouse scroll
set -g mouse on

# Set prefix to CTRL-Space
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-option -g renumber-windows on
set-window-option -g pane-base-index 1

# Reduce the delay that Tmux waits for key combinations (is making NVIM not
# working properly)

set -s escape-time 0

# -----
# Binds
# -----

# Split panes. New split opens on current directory
unbind '"'
unbind %
bind e split-window -h -c "#{pane_current_path}"
bind o split-window -v -c "#{pane_current_path}"

# Clear screen
bind-key -n C-X clear # clear the screen

# Copy and Paste on Linux
bind -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "xclip -i -f -selection primary | xclip -i -selection clipboard"
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xclip -selection clipboard -i"
set-option -s set-clipboard off

# Use `y` to copy the selection to the clipboard
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -selection clipboard -i"
# Enable Vim-style visual selection with `v` and `y` for yanking in copy mode
bind -T copy-mode-vi v send -X begin-selection

# -------
# Plugins
# -------

# Uses [tpm](https://github.com/tmux-plugins/tpm)
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'catppuccin/tmux' # color theme

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@bitbucket.com:user/plugin'
# set -g @plugin 'git@github.com:user/plugin'

# ----------------------
# Plugins configurations
# ----------------------

# Configure the catppuccin plugin
# leave this unset to let applications set the window title
set -g @catppuccin_window_default_text " #W"
set -g @catppuccin_window_current_text " #W"
# set -g @catppuccin_window_status "icon"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
