# set command flags
# -F expands formats in the option value
# -g global option
# -a appends to the existing setting if option expects a string or a style


# Set true color
set -g default-terminal "$TERM"
set -ga terminal-overrides ",$TERM:Tc"

# Allow mouse scroll
set -g mouse on

# Set prefix to CTRL-Space
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Set prefix to reload config file
bind r source-file ~/.config/tmux/tmux.conf ";" display-message "Config reloaded!"

# Move status bar to top
set-option -g status-position top

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-option -g renumber-windows on
set-window-option -g pane-base-index 1

# Reduce the delay that Tmux waits for key combinations (is making NVIM not
# working properly)

set -s escape-time 0

# -----
# Binds
# -----

# Reorder windows
bind-key -n C-M-Left swap-window -d -t -1
bind-key -n C-M-Right swap-window -d -t +1

# Split panes. New split opens on current directory
unbind '"'
unbind %
bind e split-window -h -c "#{pane_current_path}"
bind o split-window -v -c "#{pane_current_path}"

# Clear screen
# bind-key -T C-M-L clear-history # clear the screen (not working)

# Copy and Paste on Linux
bind -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "xclip -i -f -selection primary | xclip -i -selection clipboard"
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xclip -selection clipboard -i"
set-option -s set-clipboard off

# Use `y` to copy the selection to the clipboard
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -selection clipboard -i"
# Enable Vim-style visual selection with `v` and `y` for yanking in copy mode
bind -T copy-mode-vi v send -X begin-selection

# -------
# Plugins
# -------

# Uses [tpm](https://github.com/tmux-plugins/tpm)
# List of plugins
set -g @plugin 'tmux-plugins/tpm' # tmux plugin manager
set -g @plugin 'christoomey/vim-tmux-navigator' # integrates switching panes
set -g @plugin 'catppuccin/tmux' # color theme
set -g @plugin 'tmux-plugins/tmux-cpu'

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@bitbucket.com:user/plugin'
# set -g @plugin 'git@github.com:user/plugin'

# ----------------------
# Plugins configurations
# ----------------------

# Configure the catppuccin plugin
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_default_text " #W"
set -g @catppuccin_window_current_text " #W"

# Load catppuccin
run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux
# run ~/.config/tmux/plugins/tmux-plugins/tmux-cpu/cpu.tmux
# For TPM, instead use `run ~/.config/tmux/plugins/tmux/catppuccin.tmux`


# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_session}"
set -ga status-right "#{E:@catppuccin_status_date_time}"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'
